AY2324S2-CS2103-F15-1/tp

docs/UserGuide.md
=> Update UG command formats

docs/UserGuide.md
=> Add input formats to UG

docs/UserGuide.md
=> Fix alert box for user guide

docs/DeveloperGuide.md
- Update target user to financial advisors
- Update value proposition to align with group's proposed value proposition
- Update user stories table
Closes #31
=> Update target user and user stories in DG

docs/UserGuide.md
=> Add docs for `schedule` and `unschedule` command

docs/UserGuide.md
Update user guide of Edit command
Change the examples to be more specific and representative
Add description of **phone number check** to the user guide
=> Update User Guide for Edit command

src/main/java/seedu/findvisor/ui/HelpWindow.java
Change help window url to redirect users from old addressbook UG to FINDvisor UG.
Closes #29
=> Update help window

docs/UserGuide.md
=> Update command summary in UG

src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
=> Add missing meeting fields for json test files

build.gradle
=> Rename JAR filename to findvisor.jar

src/main/java/seedu/findvisor/MainApp.java, src/main/resources/view/MainWindow.fxml
=> Update title bar text to FINDvisor

copyright.txt, src/main/java/seedu/findvisor/ui/UiManager.java
=> Fix icon path in UiManager

docs/DeveloperGuide.md
=> Update DG to use correct package name

src/main/java/seedu/findvisor/logic/Messages.java, src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java, src/main/java/seedu/findvisor/logic/parser/CliSyntax.java, src/main/java/seedu/findvisor/logic/parser/ScheduleCommandParser.java, src/main/java/seedu/findvisor/model/person/Meeting.java, src/main/java/seedu/findvisor/storage/JsonAdaptedMeeting.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/findvisor/logic/MessagesTest.java, src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java, src/test/java/seedu/findvisor/logic/commands/ScheduleCommandTest.java, src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java, src/test/java/seedu/findvisor/logic/parser/ScheduleCommandParserTest.java, src/test/java/seedu/findvisor/model/person/MeetingTest.java, src/test/java/seedu/findvisor/storage/JsonAdaptedMeetingTest.java, src/test/java/seedu/findvisor/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/findvisor/testutil/TypicalPersons.java
- Add remark field to meeting
- Update json test files
- Fix checkstyle issues
- Update existing tests to work with remark
- Meeting equality now also depends on remark
- Update tests for JsonAdaptedMeeting
- Update schedule command tests
- Update json adapted tests
- Update ScheduleCommand usage message
=> Feature: Meeting's can store remark

src/main/java/seedu/findvisor/logic/Messages.java, src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java, src/main/java/seedu/findvisor/logic/parser/ScheduleCommandParser.java, src/main/java/seedu/findvisor/model/person/Meeting.java, src/main/java/seedu/findvisor/storage/JsonAdaptedMeeting.java, src/test/java/seedu/findvisor/logic/commands/ScheduleCommandTest.java, src/test/java/seedu/findvisor/logic/parser/ScheduleCommandParserTest.java, src/test/java/seedu/findvisor/model/person/MeetingTest.java
https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking
=> Claim authorship for code written prior to 23 Feb

src/main/java/seedu/findvisor/commons/util/StringUtil.java, src/test/java/seedu/findvisor/commons/util/StringUtilTest.java
Required to fix issue #153 and #157 as the regex will be used to validate if the input for remark should be accepted.
=> Add safe string check

src/main/java/seedu/findvisor/model/person/Address.java, src/test/java/seedu/findvisor/model/person/AddressTest.java
- Change address validation regex from any character to alphanumeric + "#-()," special characters
Fixes #152
=> Update validation regex for addresses

docs/UserGuide.md
=> Update quantifier in command format definition

src/main/java/seedu/findvisor/logic/commands/FindCommand.java, src/main/java/seedu/findvisor/logic/parser/CliSyntax.java, src/main/java/seedu/findvisor/logic/parser/FindCommandParser.java, src/main/java/seedu/findvisor/model/person/PersonAddressPredicate.java, src/main/java/seedu/findvisor/model/person/PersonEmailPredicate.java, src/main/java/seedu/findvisor/model/person/PersonMeetingPredicate.java, src/main/java/seedu/findvisor/model/person/PersonMeetingRemarkPredicate.java, src/main/java/seedu/findvisor/model/person/PersonNamePredicate.java, src/main/java/seedu/findvisor/model/person/PersonPhonePredicate.java, src/main/java/seedu/findvisor/model/person/PersonRemarkPredicate.java, src/main/java/seedu/findvisor/model/tag/PersonTagsPredicate.java, src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java, src/test/java/seedu/findvisor/logic/commands/FindCommandTest.java, src/test/java/seedu/findvisor/logic/parser/FindCommandParserTest.java, src/test/java/seedu/findvisor/model/person/PersonEmailPredicateTest.java, src/test/java/seedu/findvisor/model/person/PersonMeetingRemarkPredicateTest.java, src/test/java/seedu/findvisor/model/person/PersonRemarkPredicateTest.java
- Meeting remark prefix has been modified from `r/` to `mr/`
Closes #164
=> Allow users to find persons by remark and meeting remark 

docs/UserGuide.md
- `find` command description matches v1.3 implementation
- Replace all instances of `PHONE` to `PHONE_NUMBER` in UG
Closes #124
=> Update find command description in UG

docs/DeveloperGuide.md, docs/UserGuide.md
Updated the following items in UG:
1. Add remark constraints.
2. Add remark command usage.
3. Add remark to command table summary
Updated the following items in DG:
1. Add remark use case.
Closes #118 and closes #119
=> Update remark documentation

src/main/resources/view/PersonListCard.fxml
=> Fix PersonCard text wrap

docs/DeveloperGuide.md
=> Update target user profile

src/main/java/seedu/findvisor/commons/core/GuiSettings.java
GUI default settings is now configured to be representative of Ui.png
=> Update default GUI settings

docs/UserGuide.md
=> Add page break

docs/UserGuide.md
=> Update description for find result for tags

docs/UserGuide.md
=> Update remark value format to be optional

docs/UserGuide.md
=> Update UG to specify non-blank constraint

docs/UserGuide.md
=> Revert file saved file name in UG to addressbook.json

docs/UserGuide.md
=> Update name constraint in ug to alphanumeric

docs/UserGuide.md
=> Standardize blank parameter specification

docs/DeveloperGuide.md
=> Add planned enhancements for remarks and address

docs/UserGuide.md
Change the description of delete command
=> Update UG for deletion

src/main/java/seedu/findvisor/model/tag/PersonTagsPredicate.java
- Add stack overflow reuse links
=> Add reuse links

docs/DeveloperGuide.md
=> Remove proposed changes from DG

src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java, src/main/java/seedu/findvisor/logic/Messages.java, src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java, src/main/java/seedu/findvisor/model/person/Meeting.java, src/main/java/seedu/findvisor/model/person/PersonMeetingPredicate.java, src/main/java/seedu/findvisor/model/person/PersonTodayMeetingsPredicate.java, src/main/java/seedu/findvisor/storage/JsonAdaptedMeeting.java, src/test/java/seedu/findvisor/logic/MessagesTest.java, src/test/java/seedu/findvisor/logic/commands/FindCommandTest.java, src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java, src/test/java/seedu/findvisor/logic/parser/RescheduleCommandParserTest.java, src/test/java/seedu/findvisor/logic/parser/ScheduleCommandParserTest.java
- Refactor meeting fields to private in main code
- Fix compilation errors for tests
- Update javadoc examples for datetimes
=> Refactor meeting fields to private

src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java, src/main/java/seedu/findvisor/model/person/Meeting.java
=> Revert date format in find error message

docs/DeveloperGuide.md
=> Fix use cases and user stories

docs/DeveloperGuide.md
Closes #297 
Visual render of developer guide:
Note that the link points to the proposed implementation of the undo and redo feature.
=> Add undo redo enhancement

docs/DeveloperGuide.md
- Edited launch and shutdown section
- Added adding a person section
- Added a note about list of alternative test cases
Related to #298
=> Update manual testing appendix

docs/DeveloperGuide.md
Related to #298 
Added the following sections under test appendix:
1. Delete command
2. Remark command
3. Clear command
4. Help command
5. List command
=> Add more test appendix

docs/DeveloperGuide.md
=> Include addtag and deletetag test cases in DG

docs/DeveloperGuide.md
- Change undo redo enhancement to confirmation prompt
- Removed implementation for undo redo
Closes #321
=> Update undo redo to clear command enhancement

docs/DeveloperGuide.md
=> Add test cases for list, edit and find in DG

README.md, docs/DeveloperGuide.md, docs/UserGuide.md, docs/index.md
- Update description of FINDvisor in index.md
- Update description of FINDvisor in UG
-  Update description of FINDvisor in README
- Add acknowledgements in DG
=> Update description of FINDvisor in index.md

docs/DeveloperGuide.md
Update test cases for schedule and unschedule command
=> Update test cases for schedule and unschedule command

docs/DeveloperGuide.md
=> Add test cases for reschedule command
